name: 'rest_pubsub'
description: 'REST based client for performing Pub/Sub operations within Dart and Flutter.'
version: '1.0.2+8'
homepage: 'https://github.com/peiffer-innovations/rest_pubsub'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  googleapis: '^11.4.0'
  googleapis_auth: '^1.4.1'
  logging: '^1.2.0'
  meta: '^1.10.0'

dev_dependencies:
  flutter_lints: '^3.0.1'
  test: '^1.24.9'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'uuid'
  - 'vector_math'
  - 'webdriver'
