name: 'rest_pubsub'
description: 'REST based client for performing Pub/Sub operations within Dart and Flutter.'
version: '1.0.0'
homepage: 'https://github.com/peiffer-innovations/rest_pubsub'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  googleapis: '^9.1.0'
  googleapis_auth: '^1.3.1'
  logging: '^1.0.2'
  meta: '^1.7.0'

dev_dependencies: 
  test: '^1.21.2'

ignore_updates: 
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'

