name: 'rest_pubsub'
description: 'REST based client for performing Pub/Sub operations within Dart and Flutter.'
version: '1.0.1+2'
homepage: 'https://github.com/peiffer-innovations/rest_pubsub'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  googleapis: '^10.1.0'
  googleapis_auth: '^1.3.1'
  logging: '^1.1.1'
  meta: '^1.8.0'

dev_dependencies:
  test: '^1.23.1'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
